schema: "http://localhost:8055/graphql"
plugins:
    - introspection
extensions:
    codegen:
        generates:
            ./lib/types.ts:
                plugins:
                    - typescript
                    - typescript-resolvers
